update

diff --git a/dtos b/dtos
--- a/dtos
+++ b/dtos
@@ -110,7 +110,11 @@ cp ~/dotfiles/.bash_profile ~/
 # Change all scripts in .local/bin to be executable.
 find $HOME/.local/bin -type f -print0 | xargs -0 chmod 775
 
-sudo pacman -Sy dunst noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra npm nodejs moc neofetch htop github-cli acpid duf ncdu telegram-desktop wget curl tmux sd vifm ueberzug diff-so-fancy gvfs xmonad xmobar xmonad-contrib libx11 libxft libxinerama libxrandr libxinerama htop  fish
+echo "############################################################"
+echo "## Installing other package. This may take a few minutes. ##"
+echo "############################################################"
+
+sudo pacman -Sy dtos-xmonad dunst noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra npm nodejs moc neofetch htop github-cli acpid duf ncdu telegram-desktop wget curl tmux sd vifm ueberzug diff-so-fancy gvfs xmonad xmobar xmonad-contrib libx11 libxft libxinerama libxrandr libxinerama htop fish || error "failed"
 
 echo "#########################################################"
 echo "## Installing Doom Emacs. This may take a few minutes. ##"
@@ -146,11 +150,11 @@ xmonadctl_compile || echo "Compiling the xmonadctl script failed!"
                     \nLogging out is required for this take effect."
 
 echo "##############################"
-echo "## DTOS has been installed! ##"
+echo "##  has been installed! ##"
 echo "##############################"
 
 while true; do
-    read -p "Do you want to reboot to get your dtos? [Y/n] " yn
+    read -p "you want to start xmonad? [Y/n] " yn
     case $yn in
         [Yy]* ) startx;;
         [Nn]* ) break;;
